import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider, UserButton, SignedIn, SignedOut } from "@clerk/nextjs"
import { Toaster } from '@/components/ui/toaster'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}
          <Toaster />
          <div className="w-full h-9 bg-gray-200 fixed top-0">
            <SignedIn>
              <UserButton />
            </SignedIn>
            <SignedOut>
              <Link href="/sign-in">
                <button>Sign In</button>
              </Link>
            </SignedOut>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
